apiVersion: v1
kind: Service
metadata:
  name: newrelic-hello-world-service
spec:
  selector:
    app: newrelic-hello-world
  type: NodePort
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
    nodePort: 30000